"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

type AnyRow = Record<string, any>;
type WorkspaceState = {
  user: { id: string; email: string; displayName: string; role: "coach" | "athlete" };
  athletes: AnyRow[]; selectedAthlete: AnyRow | null; goals: AnyRow[]; tests: AnyRow[]; plans: AnyRow[];
  sessions: AnyRow[]; upcoming: AnyRow[]; activities: AnyRow[]; feedback: AnyRow[]; assessments: AnyRow[];
  connections: AnyRow[]; jobs: AnyRow[]; notifications: AnyRow[]; notes: AnyRow[]; metrics: AnyRow;
  testRequests: AnyRow[]; performanceSnapshots: AnyRow[];
};
type Language = "en" | "de";
type Tab = "overview" | "activities" | "plan" | "testing" | "performance" | "goals" | "feedback" | "data";
type Modal = "invite" | "goal" | "test" | "testRequest" | "performance" | "feedback" | "profile" | "onboarding" | null;

export default function DashboardClient() {
  const [state, setState] = useState<WorkspaceState | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  const [modal, setModal] = useState<Modal>(null);
  const [busy, setBusy] = useState("");
  const [loadingAthleteId, setLoadingAthleteId] = useState("");
  const [athleteSearch, setAthleteSearch] = useState("");
  const [message, setMessage] = useState<{ tone: "good" | "bad"; text: string } | null>(null);
  const [language, setLanguage] = useState<Language>("en");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const workspaceRequest = useRef<AbortController | null>(null);

  const load = useCallback(async (athleteId?: string) => {
    workspaceRequest.current?.abort();
    const controller = new AbortController(); workspaceRequest.current = controller;
    setLoadingAthleteId(athleteId ?? "initial");
    const query = athleteId ? `?athleteId=${encodeURIComponent(athleteId)}` : "";
    try {
      const response = await fetch(`/api/workspace${query}`, { cache: "no-store", signal: controller.signal });
      if (!response.ok) throw new Error(await response.text());
      const next = await response.json();
      if (workspaceRequest.current !== controller) return;
      setState(next);
      if (next.user?.role === "athlete" && !next.selectedAthlete?.onboardingCompletedAt) setModal((current) => current ?? "onboarding");
    } catch (error) {
      if (!(error instanceof DOMException && error.name === "AbortError")) setMessage({ tone: "bad", text: error instanceof Error ? error.message : "Workspace could not be loaded." });
    } finally {
      if (workspaceRequest.current === controller) setLoadingAthleteId("");
    }
  }, []);

  useEffect(() => {
    const saved = window.localStorage.getItem("pb-language");
    if (saved === "de" || saved === "en") setLanguage(saved);
    void load();
  }, [load]);

  const selectedAthleteId = state?.selectedAthlete?.id;
  const selectedHasIntervals = Boolean(state?.connections?.some((item) => item.provider === "intervals" && item.status === "active"));
  useEffect(() => {
    if (!selectedAthleteId || !selectedHasIntervals) return;
    const refresh = () => { if (document.visibilityState === "visible") void load(selectedAthleteId); };
    const timer = window.setInterval(refresh, 10 * 60 * 1000);
    document.addEventListener("visibilitychange", refresh);
    return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", refresh); };
  }, [selectedAthleteId, selectedHasIntervals, load]);

  function changeLanguage(next: Language) { setLanguage(next); window.localStorage.setItem("pb-language", next); document.documentElement.lang = next; }
  const de = language === "de";

  async function act(action: string, payload: AnyRow = {}, success = "Saved") {
    if (!state?.selectedAthlete && action !== "inviteAthlete") return;
    setBusy(action); setMessage(null);
    try {
      const response = await fetch("/api/workspace", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, athleteId: state?.selectedAthlete?.id, ...payload }) });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.error ?? "The action could not be completed.");
      setState(result.state); setModal(null); setMessage({ tone: "good", text: success });
    } catch (error) { setMessage({ tone: "bad", text: error instanceof Error ? error.message : "Unexpected error" }); }
    finally { setBusy(""); }
  }

  if (!state) return <LoadingScreen message={message?.text} />;
  if (!state.selectedAthlete) return <EmptyWorkspace user={state.user} onInvite={() => setModal("invite")} modal={modal} close={() => setModal(null)} act={act} busy={busy} />;
  const athlete = state.selectedAthlete; const coach = state.user.role === "coach";
  const activeGoal = state.goals.find((goal) => goal.status === "active") ?? state.goals[0];
  const draft = state.plans.find((plan) => plan.status === "draft"); const adjustment = state.metrics.planAdjustment;
  const latestAssessment = state.assessments[0];
  const selectTab = (next: Tab) => { setTab(next); setMobileMenuOpen(false); };

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand"><img className="brand-logo" src="/personal-besties-logo-placeholder.png" alt="Personal Besties" /></div>
        <nav aria-label="Workspace sections">
          <NavButton active={tab === "overview"} label={de ? "Übersicht" : "Overview"} icon="⌂" onClick={() => selectTab("overview")} />
          <NavButton active={tab === "activities"} label={de ? "Aktivitätsbericht" : "Activity report"} icon="◎" onClick={() => selectTab("activities")} />
          <NavButton active={tab === "plan"} label={de ? "Trainingsplan" : "Training plan"} icon="□" onClick={() => selectTab("plan")} />
          <NavButton active={tab === "testing"} label={de ? "Laktattests" : "Lactate tests"} icon="⌁" onClick={() => selectTab("testing")} />
          <NavButton active={tab === "performance"} label={de ? "Leistungstrends" : "Performance trends"} icon="↗" onClick={() => selectTab("performance")} />
          <NavButton active={tab === "goals"} label={de ? "Ziele" : "Goals"} icon="◇" onClick={() => selectTab("goals")} />
          <NavButton active={tab === "feedback"} label="Feedback" icon="◌" badge={state.feedback.length ? undefined : "1"} onClick={() => selectTab("feedback")} />
          <NavButton active={tab === "data"} label={de ? "Daten & Versand" : "Data & delivery"} icon="↻" onClick={() => selectTab("data")} />
        </nav>
        {coach && <div className="athlete-list">
          <div className="section-label">{de ? "DEINE ATHLETEN" : "YOUR ATHLETES"} <button onClick={() => setModal("invite")} aria-label={de ? "Athlet einladen" : "Invite athlete"}>+</button></div>
          <input className="athlete-search" type="search" value={athleteSearch} onChange={(event) => setAthleteSearch(event.target.value)} placeholder={de ? "Athlet suchen…" : "Search athletes…"} aria-label={de ? "Athlet nach Name suchen" : "Search athletes by name"} />
          {state.athletes.filter((item) => item.displayName.toLowerCase().includes(athleteSearch.trim().toLowerCase())).map((item) => <button className={`athlete-row ${item.id === athlete.id ? "selected" : ""}`} key={item.id} onClick={() => void load(item.id)} disabled={Boolean(loadingAthleteId)} aria-busy={loadingAthleteId === item.id}>
            <span className="avatar">{initials(item.displayName)}</span><span><strong>{item.displayName}</strong><small>{loadingAthleteId === item.id ? (de ? "Lädt…" : "Loading…") : athleteStatus(item, state)}</small></span><i aria-hidden="true" />
          </button>)}
          {!state.athletes.some((item) => item.displayName.toLowerCase().includes(athleteSearch.trim().toLowerCase())) && <p className="athlete-search-empty">{de ? "Keine Treffer" : "No matching athletes"}</p>}
        </div>}
        <div className="coach-profile"><span className="avatar dark">{initials(state.user.displayName)}</span><span><strong>{state.user.displayName.split(" ")[0]}</strong><small>{coach ? (de ? "Coach-Bereich" : "Coach workspace") : (de ? "Athletenportal" : "Athlete portal")}</small></span><a href="/auth/signout" aria-label={de ? "Abmelden" : "Sign out"}>↗</a></div>
      </aside>

      <main>
        <header className="topbar">
          <div><p className="eyebrow">{coach ? (de ? "COACH-BEREICH" : "COACH WORKSPACE") : (de ? "ATHLETEN-DASHBOARD" : "ATHLETE DASHBOARD")}</p><h1>{coach ? (de ? `Hallo ${state.user.displayName.split(" ")[0]}.` : `Good ${dayPart()}, ${state.user.displayName.split(" ")[0]}.`) : (de ? "Dein Training im Kontext." : "Your training, in context.")}</h1></div>
          <div className="top-actions"><div className="language-switch" aria-label="Language"><button className={de ? "active" : ""} onClick={() => changeLanguage("de")}>DE</button><button className={!de ? "active" : ""} onClick={() => changeLanguage("en")}>EN</button></div>{coach && <button className="primary-button" onClick={() => setModal("invite")}>+ {de ? "Athlet einladen" : "Invite athlete"}</button>}</div>
        </header>
        {message && <div className={`toast ${message.tone}`}>{message.text}<button onClick={() => setMessage(null)}>×</button></div>}
        <section className="athlete-heading">
          <div className="athlete-title"><span className="avatar large">{initials(athlete.displayName)}</span><div><h2>{athlete.displayName}</h2><p>{activeGoal ? `${activeGoal.title} · ${state.metrics.daysToGoal} ${de ? "Tage bis zum Ziel" : "days to goal"}` : (de ? "Noch kein aktives Ziel" : "No active goal yet")}</p></div></div>
          <div className="heading-actions">{connectionStatus(state.connections, language)}<button className="secondary-button" onClick={() => setModal("onboarding")}>{coach ? (de ? "Planungsprofil bearbeiten" : "Edit planning profile") : (de ? "Profil aktualisieren" : "Update profile")}</button></div>
        </section>

        <SetupChecklist athlete={athlete} coach={coach} onOnboard={() => setModal("onboarding")} onGoal={() => setModal(coach ? "goal" : "onboarding")} onTest={() => coach ? setModal("test") : setTab("testing")} onData={() => setTab("data")} />

        {tab === "overview" && <Overview state={state} assessment={latestAssessment} onOpen={(next) => setTab(next)} language={language} />}
        {tab === "activities" && <ActivitiesTab state={state} language={language} onOpenPlan={() => setTab("plan")} />}
        {tab === "plan" && <PlanTab state={state} coach={coach} draft={draft} busy={busy} act={act} />}
        {tab === "testing" && <TestingTab state={state} coach={coach} onAdd={() => setModal("test")} onRequest={() => setModal("testRequest")} />}
        {tab === "performance" && <PerformanceTab state={state} coach={coach} onAdd={() => setModal("performance")} />}
        {tab === "goals" && <GoalsTab state={state} coach={coach} onAdd={() => setModal("goal")} />}
        {tab === "feedback" && <FeedbackTab state={state} coach={coach} onAdd={() => setModal("feedback")} act={act} busy={busy} />}
        {tab === "data" && <DataTab state={state} coach={coach} busy={busy} act={act} />}
      </main>
      <MobileNavigation
        tab={tab}
        open={mobileMenuOpen}
        coach={coach}
        de={de}
        athlete={athlete}
        athletes={state.athletes}
        user={state.user}
        loadingAthleteId={loadingAthleteId}
        onToggle={() => setMobileMenuOpen((open) => !open)}
        onSelect={selectTab}
        onSelectAthlete={(id) => { setMobileMenuOpen(false); void load(id); }}
        onInvite={() => { setMobileMenuOpen(false); setModal("invite"); }}
        onProfile={() => { setMobileMenuOpen(false); setModal(coach ? "profile" : "onboarding"); }}
      />
      {modal && <ModalLayer modal={modal} athlete={athlete} close={() => setModal(null)} act={act} busy={busy} />}
    </div>
  );
}

function MobileNavigation({ tab, open, coach, de, athlete, athletes, user, loadingAthleteId, onToggle, onSelect, onSelectAthlete, onInvite, onProfile }: {
  tab: Tab; open: boolean; coach: boolean; de: boolean; athlete: AnyRow; athletes: AnyRow[]; user: WorkspaceState["user"]; loadingAthleteId: string;
  onToggle: () => void; onSelect: (tab: Tab) => void; onSelectAthlete: (id: string) => void; onInvite: () => void; onProfile: () => void;
}) {
  const primary: Array<[Tab, string, string]> = [["overview", de ? "Start" : "Home", "⌂"], ["activities", de ? "Aktivität" : "Activity", "◎"], ["plan", de ? "Plan" : "Plan", "□"], ["feedback", "Feedback", "◌"]];
  const secondary: Array<[Tab, string, string]> = [["testing", de ? "Tests" : "Tests", "⌁"], ["performance", de ? "Leistung" : "Performance", "↗"], ["goals", de ? "Ziele" : "Goals", "◇"], ["data", de ? "Daten" : "Data", "↻"]];
  return <>
    {open && <div className="mobile-sheet-backdrop" onClick={onToggle} aria-hidden="true" />}
    <section className={`mobile-sheet ${open ? "open" : ""}`} aria-label={de ? "Weitere Navigation" : "More navigation"} aria-hidden={!open}>
      <div className="mobile-sheet-handle" />
      <div className="mobile-sheet-heading"><div><p className="eyebrow">{de ? "ARBEITSBEREICH" : "WORKSPACE"}</p><h2>{de ? "Mehr für dich" : "More for you"}</h2></div><button className="mobile-sheet-close" onClick={onToggle} aria-label={de ? "Menü schließen" : "Close menu"}>×</button></div>
      <div className="mobile-section-links">{secondary.map(([key, label, icon]) => <NavButton key={key} active={tab === key} label={label} icon={icon} onClick={() => onSelect(key)} />)}</div>
      <div className="mobile-account-actions"><button onClick={onProfile}>{coach ? (de ? "Athlet bearbeiten" : "Edit athlete") : (de ? "Profil aktualisieren" : "Update profile")}</button>{coach && <button onClick={onInvite}>+ {de ? "Athlet einladen" : "Invite athlete"}</button>}<a href="/auth/signout">{de ? "Abmelden" : "Sign out"} ↗</a></div>
      {coach && <div className="mobile-athlete-switcher"><p className="section-label">{de ? "DEINE ATHLETEN" : "YOUR ATHLETES"}</p>{athletes.map((item) => <button className={`athlete-row ${item.id === athlete.id ? "selected" : ""}`} key={item.id} onClick={() => onSelectAthlete(item.id)} disabled={Boolean(loadingAthleteId)}><span className="avatar">{initials(item.displayName)}</span><span><strong>{item.displayName}</strong><small>{item.id === athlete.id ? (de ? "Aktuell ausgewählt" : "Currently selected") : (de ? "Öffnen" : "Open")}</small></span><i aria-hidden="true" /></button>)}</div>}
      <p className="mobile-user-label">{user.displayName} · {coach ? (de ? "Coach" : "Coach") : (de ? "Athlet:in" : "Athlete")}</p>
    </section>
    <nav className="mobile-bottom-nav" aria-label={de ? "Hauptnavigation" : "Primary navigation"}>{primary.map(([key, label, icon]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => onSelect(key)}><span aria-hidden="true">{icon}</span><small>{label}</small></button>)}<button className={open ? "active" : ""} onClick={onToggle} aria-expanded={open}><span aria-hidden="true">•••</span><small>{de ? "Mehr" : "More"}</small></button></nav>
  </>;
}

function Overview({ state, assessment, onOpen, language }: { state: WorkspaceState; assessment?: AnyRow; onOpen: (tab: Tab) => void; language: Language }) {
  const metrics = state.metrics; const attention = metrics.attention ?? []; const de = language === "de";
  return <>
    <section className="metric-grid" aria-label="Athlete summary">
      <article className="metric-card accent-card"><p>{de ? "Wettkampfprognose" : "Race-day forecast"}</p><strong>{metrics.forecastLow ? `${formatDuration(metrics.forecastLow)}–${formatDuration(metrics.forecastHigh)}` : (de ? "Datengrundlage wird aufgebaut" : "Building evidence")}</strong><div className="metric-meta"><span className="pill positive">{assessment?.status?.replaceAll("_", " ") ?? (de ? "Daten fehlen" : "Needs data")}</span><small>{state.goals[0]?.goal_time_seconds ? `${formatDuration(state.goals[0].goal_time_seconds)} ${de ? "Ziel" : "goal"}` : (de ? "Kein Zeitziel" : "No time goal")}</small></div></article>
      <article className="metric-card"><p>{de ? "Trainingsumfang · 28 Tage" : "Training volume · 28 days"}</p><strong>{metrics.volume28Km || "—"} <em>KM</em></strong><div className="spark-bars" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /></div><small className="delta">{de ? "Fitnesswert" : "Fitness score"} {metrics.fitnessScore || (de ? "im Aufbau" : "building")}</small></article>
      <article className="metric-card"><p>{de ? "Erholungssignal" : "Recovery signal"}</p><strong>{localRecovery(metrics.recoveryStatus, language)}</strong><div className="recovery-line"><span style={{ width: `${Math.max(8, 100 - Number(metrics.fatigueScore ?? 0))}%` }} /></div><small>{de ? "Feedback, Schmerz, Schlaf und Belastung kombiniert" : "Combine feedback, pain, sleep, and load"}</small></article>
      <article className="metric-card review-card"><p>{de ? "Coach-Aufmerksamkeit" : "Coach attention"}</p><strong>{attention.length}</strong>{attention.length ? attention.slice(0, 2).map((item: AnyRow) => <div key={item.label}><span className={`attention-dot ${item.level === "critical" ? "red" : "amber"}`} />{item.label}</div>) : <div><span className="attention-dot green" />{de ? "Keine offenen Hinweise" : "No unresolved flags"}</div>}</article>
    </section>
    <div className="content-grid">
      <section className="panel schedule-panel"><div className="panel-header"><div><p className="eyebrow">{de ? "VERÖFFENTLICHTER PLAN" : "PUBLISHED PLAN"}</p><h3>{de ? "Nächste Einheiten" : "Next sessions"}</h3></div><button onClick={() => onOpen("plan")}>{de ? "Ganzen Plan öffnen" : "View full plan"} →</button></div><SessionList sessions={state.upcoming.slice(0, 6)} /></section>
      <aside className="right-column"><section className="panel readiness-panel"><div className="panel-header"><div><p className="eyebrow">{de ? "COACHING-SIGNALE" : "COACHING SIGNALS"}</p><h3>{de ? "Aktueller Kontext" : "Current context"}</h3></div><span className="pill positive">{localRecovery(metrics.recoveryStatus, language)}</span></div>
        <div className="signal"><span>{de ? "Letzter Test" : "Latest test"}</span><b>{state.tests[0] ? formatDate(state.tests[0].test_date, language) : "—"}</b><em>{state.tests[0]?.confidence ?? (de ? "fehlt" : "missing")}</em></div>
        <div className="signal"><span>Feedback</span><b>{state.feedback[0] ? formatDate(state.feedback[0].feedback_date, language) : "—"}</b><em>{state.feedback[0]?.fatigue ? `${state.feedback[0].fatigue}/10` : (de ? "keins" : "none")}</em></div>
        <div className="signal"><span>{de ? "Datenquelle" : "Data source"}</span><b>{state.connections[0]?.provider ?? (de ? "Manuell" : "Manual")}</b><em>{state.connections[0]?.last_sync_at ? (de ? "aktuell" : "current") : "setup"}</em></div>
        <p className="insight"><span>✦</span>{assessment?.summary ?? "Add activity data, a goal, and athlete feedback to strengthen the coaching assessment."}</p>
      </section></aside>
    </div>
  </>;
}

function ActivitiesTab({ state, language, onOpenPlan }: { state: WorkspaceState; language: Language; onOpenPlan: () => void }) {
  const [range, setRange] = useState("30d"); const [hrSport, setHrSport] = useState("all"); const [movementSport, setMovementSport] = useState("run"); const de = language === "de";
  const adjustment = state.metrics.planAdjustment;
  const publishedPlan = state.plans.find((plan) => plan.status === "published");
  const publishedSessions = useMemo(() => publishedPlan ? state.sessions.filter((session) => session.plan_id === publishedPlan.id) : [], [publishedPlan, state.sessions]);
  const reviews = useMemo(() => buildActivityReviews(state.activities, publishedSessions, state.tests[0], language), [state.activities, publishedSessions, state.tests, language]);
  const rangedActivities = filterActivityRange(state.activities, range);
  const hrActivities = filterActivitiesBySport(rangedActivities, hrSport);
  const movementActivities = filterActivitiesBySport(rangedActivities, movementSport);
  const paceZoneResult = movementSport === "run" ? sessionPaceZones(movementActivities, state.tests, state.activities, state.selectedAthlete) : null;
  // Source-provided seven-zone totals do not state their bpm bounds. Prefer the
  // athlete's documented lactate-test bands so every displayed zone is legible.
  const hrZoneResult = sessionHrZones(hrActivities, state.tests, state.selectedAthlete);
  const draft = state.plans.find((plan) => plan.status === "draft");
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">{de ? "AKTIVITÄTSANALYSE" : "ACTIVITY REVIEW"}</p><h2>{de ? "Ehrlich, hilfreich und im Kontext" : "Honest, useful, and in context"}</h2><p>{de ? "Die letzten Einheiten werden mit dem veröffentlichten Plan verglichen. Gute Arbeit wird sichtbar—aber auch Auslassen, Überziehen oder unnötig schnelles Laufen." : "Recent activities are compared with the published plan. Good work is recognized, while missed sessions, overreaching, and unnecessary speed are called out clearly."}</p></div>{draft && <button className="secondary-button" onClick={onOpenPlan}>{de ? `Adaptiver Entwurf v${draft.version} prüfen` : `Review adaptive draft v${draft.version}`}</button>}</div>
    {adjustment && <div className="plan-change-banner"><strong>{de ? `Plananpassung v${adjustment.version} vorgeschlagen` : `Plan adjustment v${adjustment.version} proposed`}</strong><p>{de ? "Der veröffentlichte Plan wurde nicht still geändert. Ein neuer Entwurf erklärt die Anpassung und wartet auf Coach-Prüfung." : "The published plan was not silently changed. A new draft explains the adaptation and waits for coach review."}</p><small>{adjustment.rationale}</small></div>}
    <div className="activity-review-grid">{reviews.slice(0, 8).map((review) => <article className={`panel activity-review ${review.tone} ${review.race ? "race" : ""}`} key={review.key}><div className="activity-review-head"><span>{formatDate(review.date, language)}</span><b>{review.badge}</b></div><h3>{review.title}</h3><p>{review.summary}</p><small>{review.detail}</small></article>)}</div>
    {!reviews.length && <EmptyPanel title={de ? "Noch keine Aktivitäten" : "No activities yet"} body={de ? "Nach der ersten Synchronisierung erscheinen hier ehrliche Aktivitätsberichte." : "Honest activity reviews will appear after the first synchronization."} />}
    <div className="activity-trend-header"><div><p className="eyebrow">{de ? "INTENSITÄT NACH SPORT" : "INTENSITY BY SPORT"}</p><h3>{de ? "Zonen und Sportmetriken" : "Zones and sport metrics"}</h3></div><ActivityRangePicker value={range} setValue={setRange} language={language} /></div>
    <div className="activity-chart-grid"><section className="panel performance-panel zone-panel"><div className="performance-summary"><div><p className="eyebrow">{de ? "HERZFREQUENZ" : "HEART RATE"}</p><h3>{de ? "HF-Zonen" : "Heart-rate zones"}</h3><small>{de ? "Fünf individuelle Bereiche; Details erscheinen beim Darüberfahren." : "Five individual ranges; time details appear on hover."}</small></div><SportPicker value={hrSport} setValue={setHrSport} includeAll /></div><SessionZoneContent zones={hrZoneResult?.zones ?? null} source={hrZoneResult?.source} empty={de ? "Für diesen Zeitraum gibt es noch keine HF-Streamdaten." : "There are no HR stream samples for this selection yet."} /></section><section className="panel performance-panel zone-panel"><div className="performance-summary"><div><p className="eyebrow">{movementSport === "cycle" ? "CYCLING" : "PACE"}</p><h3>{movementSport === "cycle" ? (de ? "Radfahren: Tempo & Leistung" : "Cycling: speed & power") : (de ? "Pace-Zonen" : "Pace zones")}</h3><small>{movementSport === "cycle" ? (de ? "Kilometer pro Stunde und Durchschnittsleistung." : "Kilometres per hour and average power.") : (de ? "Sechs individuelle Bereiche; Herkunft und Zeitpunkt stehen darunter." : "Six individual ranges; the evidence and date are shown below.")}</small></div><SportPicker value={movementSport} setValue={setMovementSport} /></div>{movementSport === "cycle" ? <CyclingMetrics activities={movementActivities} /> : movementSport === "run" ? <SessionZoneContent zones={paceZoneResult?.zones ?? null} source={paceZoneResult?.source} empty={de ? "Für diesen Zeitraum gibt es noch keine Pace-Streamdaten." : "There are no pace stream samples for this selection yet."} /> : <div className="chart-empty zone-empty">Select running for pace zones or cycling for speed and power.</div>}</section></div>
  </section>;
}

function SessionZoneContent({ zones, empty, source }: { zones:ZoneShare[] | null; empty:string; source?:string }) { return zones ? <><div className="zone-bars" role="img" aria-label="Zone distribution">{zones.map((zone) => <button className="zone-bar" key={zone.label} style={{ "--zone-share": `${Math.max(3, zone.share)}%` } as React.CSSProperties} aria-label={`${zone.label}: ${zone.share}%`}><span className="zone-bar-fill" /><strong>{zone.share}%</strong><em>{zone.label}</em><small>{zone.hint}</small><b>{zone.count} of {zone.total} minutes</b></button>)}</div>{source && <p className="zone-explainer">{source}</p>}</> : <div className="chart-empty zone-empty"><span>{empty}</span>{source && <small>{source}</small>}</div>; }
function SportPicker({ value, setValue, includeAll=false }: { value:string; setValue:(value:string)=>void; includeAll?:boolean }) { const options=includeAll?[['all','All'],['run','Run'],['cycle','Cycle'],['other','Other']]:[['run','Run'],['cycle','Cycle'],['other','Other']]; return <div className="sport-picker">{options.map(([key,label])=><button key={key} className={value===key?"active":""} onClick={()=>setValue(key)}>{label}</button>)}</div>; }
function ActivityRangePicker({ value, setValue, language }: { value:string; setValue:(value:string)=>void; language:Language }) { const de=language==="de"; return <div className="range-picker activity-range-picker">{[["7d",de?"1W":"1W"],["30d",de?"1M":"1M"],["90d",de?"3M":"3M"],["180d",de?"6M":"6M"],["365d",de?"1J":"1Y"],["all",de?"Alle":"All"]].map(([key,label])=><button key={key} className={value===key?"active":""} onClick={()=>setValue(key)}>{label}</button>)}</div>; }
function CyclingMetrics({ activities }: { activities:AnyRow[] }) { const speeds=activities.map((item)=>Number(item.distance_km)/Number(item.duration_seconds)*3600).filter((value)=>Number.isFinite(value)&&value>3&&value<100); const watts=activities.map(activityWatts).filter((value):value is number=>value!==null); if(!speeds.length)return <div className="chart-empty zone-empty">No cycling activities with usable distance and duration in this period.</div>; return <div className="cycling-metrics"><div><span>Median speed</span><strong>{median(speeds).toFixed(1)} km/h</strong><small>{speeds.length} rides</small></div><div><span>Median power</span><strong>{watts.length ? `${Math.round(median(watts))} W` : "—"}</strong><small>{watts.length ? `${watts.length} rides with power` : "No power data supplied"}</small></div></div>; }

function SetupChecklist({ athlete, coach, onOnboard, onGoal, onTest, onData }: { athlete:AnyRow; coach:boolean; onOnboard:()=>void; onGoal:()=>void; onTest:()=>void; onData:()=>void }) {
  const setup=athlete.setup ?? {}; const steps=[["profile","Profile",onOnboard],["goal","Goal",onGoal],["connection","Data",onData],["activities","History",onData],["lactate","Lactate",onTest]] as const;
  const complete=steps.filter(([key])=>setup[key]).length;
  if(complete===steps.length) return null;
  return <section className="setup-strip"><div><p className="eyebrow">ATHLETE SETUP · {complete}/{steps.length}</p><strong>{coach ? "Finish the athlete foundation before generating the first plan." : "Complete your setup so your coach can build the right plan."}</strong></div><div className="setup-steps">{steps.map(([key,label,action])=><button key={key} className={setup[key]?"done":""} onClick={action}><i>{setup[key]?"✓":"·"}</i>{label}</button>)}</div></section>;
}

function PlanTab({ state, coach, draft, busy, act }: { state: WorkspaceState; coach: boolean; draft?: AnyRow; busy: string; act: (action: string, payload?: AnyRow, success?: string) => void }) {
  const [filter, setFilter] = useState("upcoming"); const [view, setView] = useState<"published" | "draft">("published"); const plans = state.plans;
  const publishedPlan = plans.find((plan) => plan.status === "published"); const reviewingDraft = view === "draft" && Boolean(draft);
  const selectedPlan = reviewingDraft ? draft : publishedPlan ?? draft ?? plans[0];
  const today = new Date().toISOString().slice(0,10); const fourWeeks = new Date(Date.now() + 28 * 86400000).toISOString().slice(0,10);
  const sessions = state.sessions.filter((session) => !selectedPlan || session.plan_id === selectedPlan.id).filter((session) => filter === "all" || (session.session_date >= today && session.session_date <= fourWeeks));
  const readiness = state.metrics.planReadiness ?? { ready:true, reasons:[] };
  const planDiff = reviewingDraft && draft && publishedPlan ? comparePlans(state.sessions.filter((session) => session.plan_id === publishedPlan.id), state.sessions.filter((session) => session.plan_id === draft.id)) : null;
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">TRAINING PLAN</p><h2>{selectedPlan ? `Version ${selectedPlan.version} · ${selectedPlan.status}` : "No plan yet"}</h2><p>{selectedPlan?.rationale ?? "Create a goal first, then generate a coach-reviewed draft."}</p></div>{coach && <div className="hero-actions">{draft && <button className="secondary-button" onClick={() => setView(reviewingDraft ? "published" : "draft")}>{reviewingDraft ? "Back to published plan" : `Review draft v${draft.version}`}</button>}<button className="secondary-button" disabled={Boolean(busy) || !readiness.ready} title={!readiness.ready ? readiness.reasons.join(" ") : undefined} onClick={() => act("generatePlan", {}, "A new draft plan was generated")}>{busy === "generatePlan" ? "Generating…" : "+ Generate draft"}</button>{reviewingDraft && draft && <button className="primary-button" disabled={Boolean(busy)} onClick={() => act("publishPlan", { planId: draft.id }, "Plan published and delivery queued")}>Publish v{draft.version}</button>}</div>}</div>
    {coach && <div className={`plan-readiness ${readiness.ready ? "ready" : "blocked"}`}><strong>{readiness.ready ? "Ready for an individual running draft" : "Draft generation needs more athlete information"}</strong>{readiness.ready ? <span>Current volume, experience, availability, health confirmation, goal, and recent activity context are available. Coach review is still required before publishing.</span> : <ul>{readiness.reasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul>}</div>}
    {planDiff && <div className="plan-diff"><strong>Draft changes versus published plan</strong><span>{planDiff.changed} changed · {planDiff.added} added · {planDiff.removed} removed sessions</span><small>Compare these changes before publishing; the current plan stays live until you approve the draft.</small></div>}
    <div className="toolbar"><div className="segmented"><button className={filter === "upcoming" ? "active" : ""} onClick={() => setFilter("upcoming")}>Next 4 weeks</button><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Full plan</button></div>{plans.some((plan) => plan.status === "published") && <a className="secondary-button link-button" href={`/api/calendar?athleteId=${state.selectedAthlete?.id}`}>Download calendar</a>}</div>
    {state.metrics.dueSessions > 0 && <div className="plan-summary"><span><strong>{state.metrics.adherencePercent}%</strong> adherence</span><span>{state.metrics.completedSessions} of {state.metrics.dueSessions} due sessions completed</span></div>}
    <section className="panel"><SessionList sessions={sessions} expanded coach={coach} editable={selectedPlan?.status === "draft"} canLog={!coach && selectedPlan?.status === "published"} busy={busy} act={act} /></section>
  </section>;
}

function comparePlans(published:AnyRow[], draft:AnyRow[]) { const signature=(session:AnyRow)=>[session.title,session.workout_type,Number(session.planned_distance_km??0),session.pace_guidance,session.hr_guidance].join("|"); const oldByDate=new Map(published.map((session)=>[String(session.session_date),signature(session)])); const newByDate=new Map(draft.map((session)=>[String(session.session_date),signature(session)])); let changed=0,added=0,removed=0; for(const [date,value] of newByDate) oldByDate.has(date) ? changed+=Number(oldByDate.get(date)!==value) : added+=1; for(const date of oldByDate.keys()) if(!newByDate.has(date)) removed+=1; return {changed,added,removed}; }

function TestingTab({ state, coach, onAdd, onRequest }: { state: WorkspaceState; coach: boolean; onAdd: () => void; onRequest: () => void }) {
  const [selected, setSelected] = useState<string[]>(state.tests.slice(0, 2).map((test) => String(test.id)));
  const compared = state.tests.filter((test) => selected.includes(String(test.id))).slice(0, 4);
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 4 ? [...current, id] : current); }
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">PHYSIOLOGICAL TESTING</p><h2>Lactate tests</h2><p>See your latest thresholds, inspect what LT1 and LT2 mean, and overlay up to four tests to make progress visible.</p></div><div className="hero-actions"><button className="secondary-button" onClick={onRequest}>Request next test</button>{coach && <button className="primary-button" onClick={onAdd}>+ Record test</button>}</div></div>
    {state.tests.length ? <><section className="panel comparison-panel"><div className="panel-header"><div><p className="eyebrow">TEST COMPARISON</p><h3>Overlaid lactate curves</h3></div><span className="comparison-help" data-tooltip="Compare like-for-like protocols where possible. A rightward shift at the same lactate level generally indicates improved sustainable speed.">ⓘ</span></div><div className="test-selector">{state.tests.map((test, index) => <button key={test.id} className={selected.includes(String(test.id)) ? "selected" : ""} onClick={() => toggle(String(test.id))}><i style={{background: chartColor(index)}} />{formatDate(test.test_date)}</button>)}</div><LactateOverlay tests={compared} allTests={state.tests} /></section>
      <div className="test-history-heading"><div><p className="eyebrow">TEST HISTORY</p><h3>Latest results</h3></div>{state.testRequests[0] && <span className="pill muted-pill">Next test {state.testRequests[0].status}</span>}</div>
      {state.tests.map((test, index) => <article className="panel test-card" key={test.id}><div className="panel-header"><div><p className="eyebrow">{index === 0 ? "LATEST · " : ""}{formatDate(test.test_date)} · {test.venue || "Venue not recorded"}</p><h3>{test.protocol}</h3></div><span className="pill positive">{test.confidence} confidence</span></div><div className="threshold-grid"><Threshold label="LT1" pace={test.lt1_pace_seconds_km} hr={test.lt1_hr} lactate={test.lt1_lactate} help="LT1 is the first lactate threshold: the upper edge of easy, sustainable aerobic work. It is useful for easy-run and endurance intensity guidance." /><Threshold label="LT2" pace={test.lt2_pace_seconds_km} hr={test.lt2_hr} lactate={test.lt2_lactate} help="LT2 is the second lactate threshold: the highest intensity that can be sustained before lactate accumulates rapidly. It guides threshold sessions and race modelling." /></div>{test.stages?.length > 0 && <details className="stage-details"><summary>View {test.stages.length} protocol stages</summary><div className="stage-table"><table><thead><tr><th>Stage</th><th>Pace</th><th>HR</th><th>Lactate</th><th>RPE</th></tr></thead><tbody>{test.stages.map((stage: AnyRow) => <tr key={stage.id}><td>{stage.stage_number}</td><td>{formatPace(stage.pace_seconds_km)}</td><td>{stage.heart_rate ?? "—"}</td><td>{stage.lactate_mmol} mmol/L</td><td>{stage.rpe ?? "—"}</td></tr>)}</tbody></table></div></details>}<p className="card-note">{test.notes || "No interpretation notes."}</p></article>)}</> : <EmptyPanel title="No test recorded" body="Request your first test, or let your coach add the complete protocol and stage observations." />}
  </section>;
}

function LactateOverlay({ tests, allTests }: { tests: AnyRow[]; allTests: AnyRow[] }) {
  const maxStages = Math.max(2, ...tests.map((test) => test.stages?.length ?? 0));
  const maxLactate = Math.max(6, ...tests.flatMap((test) => (test.stages ?? []).map((stage: AnyRow) => Number(stage.lactate_mmol ?? 0))));
  if (!tests.length) return <div className="chart-empty">Select at least one test to compare.</div>;
  return <div className="lactate-chart-wrap"><div className="axis-label y-label">Lactate mmol/L</div><div className="lactate-chart" role="img" aria-label="Overlaid lactate test stages"><div className="chart-grid" />{tests.flatMap((test) => { const color = chartColor(Math.max(0, allTests.findIndex((item) => item.id === test.id))); return (test.stages ?? []).map((stage: AnyRow, index: number) => <button className="lactate-point" key={`${test.id}-${stage.id}`} style={{left:`${6 + index / (maxStages - 1) * 88}%`,bottom:`${8 + Number(stage.lactate_mmol) / maxLactate * 82}%`,background:color}} aria-label={`${formatDate(test.test_date)}, ${formatPace(stage.pace_seconds_km)}, ${stage.lactate_mmol} millimoles per litre`}><span>{formatPace(stage.pace_seconds_km)}<b>{stage.lactate_mmol} mmol/L · {stage.heart_rate ?? "—"} bpm</b></span></button>);})}</div><div className="axis-label x-label">Faster stages →</div></div>;
}

function PerformanceTab({ state, coach, onAdd }: { state: WorkspaceState; coach: boolean; onAdd: () => void }) {
  const [distance, setDistance] = useState("half"); const [range, setRange] = useState("all");
  const snapshots = state.performanceSnapshots;
  const forecastPoints = snapshots.map((item) => ({ date:item.snapshot_date, value:Number(item[`prediction_${distance}_seconds`]), source:item.source, kind:"prediction" as const })).filter((item) => item.value > 0);
  const predictionPoints = filterRange(forecastPoints.sort((a,b) => a.date.localeCompare(b.date)), range);
  const realPoints = filterRange(realPerformancePoints(state.activities, distance), range);
  const trendPoints = [...predictionPoints, ...realPoints].sort((a,b) => a.date.localeCompare(b.date));
  const vo2Points = filterRange(snapshots.map((item) => ({date:item.snapshot_date,value:Number(item.vo2max),source:item.source,kind:"device" as const})).filter((item) => item.value > 0), range);
  const latest = predictionPoints.at(-1);
  const evidence = state.metrics.forecastEvidence; const confidence = state.metrics.forecastConfidence;
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">PERFORMANCE TRENDS</p><h2>Predictions & VO₂max</h2><p>Follow changes over your complete history—not only the last six months. Device estimates retain their original source; model points are recorded weekly after each sync.</p></div>{coach && <button className="primary-button" onClick={onAdd}>+ Add data point</button>}</div>
    <div className="performance-tabs">{[["5k","5K"],["10k","10K"],["half","Half marathon"],["marathon","Marathon"]].map(([value,label]) => <button className={distance===value?"active":""} key={value} onClick={()=>setDistance(value)}>{label}</button>)}</div>
    <section className="panel performance-panel"><div className="performance-summary"><div><p className="eyebrow">CURRENT PREDICTION</p><strong>{latest ? formatDuration(latest.value) : "Building evidence"}</strong><small>{latest ? `${formatDate(latest.date)} · ${latest.source}` : "Sync activity history to build a conservative estimate"}</small></div><div className="performance-volume"><p className="eyebrow">RECENT RUNNING VOLUME</p><strong>{state.metrics.weeklyKm ?? 0} km/week</strong><small>Last 28 days; cycling is excluded</small></div><RangePicker value={range} setValue={setRange} /></div><TrendLegend /><TrendChart points={trendPoints} formatter={formatDuration} inverted label={`${distanceLabel(distance)} prediction and real effort`} />{confidence && <div className={`forecast-confidence ${confidence}`}><strong>{confidence} confidence</strong><span>{evidence ? `${evidence.raceLikeRuns} race-like run${evidence.raceLikeRuns === 1 ? "" : "s"}, ${evidence.eligibleRuns} eligible runs, ${evidence.longestRunKm} km longest run.` : "A forecast needs recent race-like evidence to be well calibrated."}</span></div>}<p className="chart-footnote">Green points are model predictions. Orange points are real efforts at this distance; purple points are recorded races. No activity is converted into an "actual" result at another distance.</p></section>
    <section className="panel performance-panel vo2-panel"><div className="performance-summary"><div><p className="eyebrow">AEROBIC FITNESS</p><h3>VO₂max history</h3><small>Garmin, Suunto, COROS, Intervals.icu, or manual lab values</small></div><RangePicker value={range} setValue={setRange} /></div>{vo2Points.length ? <TrendChart points={vo2Points} formatter={(value)=>value.toFixed(1)} label="VO2max" /> : <div className="chart-empty tall">No VO₂max value has been supplied by the connected device or Intervals.icu yet.{coach && <button className="secondary-button inline-action" onClick={onAdd}>Add a measured or device value</button>}</div>}<p className="chart-footnote">Personal Besties imports device, activity, wellness, and profile VO₂max when exposed by Intervals.icu. It will not derive a laboratory VO₂max from pace alone; a measured/device value can be added with its source and date.</p></section>
  </section>;
}

function RangePicker({ value, setValue }: { value:string; setValue:(value:string)=>void }) { return <div className="range-picker">{[["3m","3M"],["6m","6M"],["1y","1Y"],["all","All"]].map(([key,label])=><button key={key} className={value===key?"active":""} onClick={()=>setValue(key)}>{label}</button>)}</div>; }
function TrendLegend() { return <div className="trend-legend"><span className="prediction">Model prediction</span><span className="effort">Real effort</span><span className="race">Race</span></div>; }
function TrendChart({ points, formatter, inverted=false, label }: { points:{date:string;value:number;source:string;kind?:"prediction"|"effort"|"race"|"device"}[]; formatter:(value:any)=>string; inverted?:boolean; label:string }) { if (!points.length) return <div className="chart-empty tall">No historical data for this view yet.</div>; const values=points.map((point)=>point.value),min=Math.min(...values),max=Math.max(...values),span=Math.max(1,max-min); return <div className="trend-chart" role="img" aria-label={label}><div className="chart-grid" />{points.map((point,index)=>{const normalized=(point.value-min)/span;const bottom=12+(inverted?1-normalized:normalized)*72;const kind=point.kind??"prediction";return <button key={`${point.date}-${index}-${kind}`} className={`trend-point ${kind}`} style={{left:`${6+index/Math.max(1,points.length-1)*88}%`,bottom:`${bottom}%`}}><span>{formatDate(point.date)}<b>{formatter(point.value)} · {point.source}</b></span></button>;})}<div className="trend-start">{formatDate(points[0].date)}</div><div className="trend-end">{formatDate(points.at(-1)?.date)}</div></div>; }

function GoalsTab({ state, coach, onAdd }: { state: WorkspaceState; coach: boolean; onAdd: () => void }) {
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">GOALS & EVENTS</p><h2>Race roadmap</h2><p>Priority determines which event controls the current plan and taper. Trail elevation and terrain shape hill and long-run preparation.</p></div>{coach && <button className="primary-button" onClick={onAdd}>+ Add goal</button>}</div><div className="goal-list">{state.goals.length ? state.goals.map((goal) => <article className="panel goal-card" key={goal.id}><div className={`priority priority-${String(goal.priority).toLowerCase()}`}>{goal.priority}</div><div><p className="eyebrow">{formatDate(goal.event_date)} · {goal.distance_km ? `${goal.distance_km} km` : "Event"}{goal.elevation_gain_m ? ` · ${Math.round(Number(goal.elevation_gain_m)).toLocaleString()} m+` : ""}{goal.terrain_type ? ` · ${goal.terrain_type}` : ""}</p><h3>{goal.title}</h3><p>{goal.notes || "No additional notes."}</p></div><div className="goal-time"><small>Target</small><strong>{goal.goal_time_seconds ? formatDuration(goal.goal_time_seconds) : "Finish goal"}</strong><span className="pill positive">{goal.status}</span></div></article>) : <EmptyPanel title="No goals yet" body="Add an event date, distance, priority, and optional target time." />}</div></section>;
}

function FeedbackTab({ state, coach, onAdd, act, busy }: { state: WorkspaceState; coach: boolean; onAdd: () => void; act: (a:string,p?:AnyRow,s?:string)=>void; busy:string }) {
  const [note, setNote] = useState("");
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">ATHLETE FEEDBACK</p><h2>Recovery and conversation</h2><p>Subjective feedback is shown beside load data; it never gets silently converted into a diagnosis.</p></div><button className="primary-button" onClick={onAdd}>+ Daily check-in</button></div><div className="feedback-grid"><div className="panel feedback-list">{state.feedback.length ? state.feedback.map((item) => <article className="feedback-item" key={item.id}><div className="feedback-date"><strong>{new Date(`${item.feedback_date}T12:00:00Z`).getUTCDate()}</strong><span>{new Date(`${item.feedback_date}T12:00:00Z`).toLocaleDateString("en",{month:"short",timeZone:"UTC"})}</span></div><div><strong>{item.pain ? "Pain reported" : "Daily check-in"}</strong><p>{item.comments || item.pain || "No comments."}</p><div className="feedback-chips"><span>Fatigue {item.fatigue ?? "—"}/10</span><span>Legs {item.legs ?? "—"}/10</span><span>Sleep {item.sleep ?? "—"}/10</span></div></div></article>) : <EmptyPanel title="No feedback yet" body="The athlete can submit fatigue, legs, sleep, pain, and comments." />}</div>{coach && <aside className="panel note-panel"><p className="eyebrow">PRIVATE COACH NOTES</p><h3>Notes are coach-only</h3><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Capture context, a follow-up question, or your plan decision…" /><button className="primary-button" disabled={!note.trim() || Boolean(busy)} onClick={() => { act("saveCoachNote", { note }, "Private note saved"); setNote(""); }}>Save note</button><div className="note-history">{state.notes.map((item) => <p key={item.id}>{item.body}<small>{formatDateTime(item.created_at)}</small></p>)}</div></aside>}</div></section>;
}

function DataTab({ state, coach, busy, act }: { state: WorkspaceState; coach: boolean; busy: string; act: (a:string,p?:AnyRow,s?:string)=>void }) {
  const connection = state.connections.find((item) => item.provider === "intervals");
  const hasIntervalsVo2 = state.performanceSnapshots.some((item) => Number(item.vo2max) > 0 && /intervals|garmin|suunto|coros|polar/i.test(String(item.source)));
  return <section className="workspace-section"><div className="section-hero"><div><p className="eyebrow">DATA & DELIVERY</p><h2>Private connections</h2><p>Each athlete authorizes their own source. Tokens are encrypted and never shown in the dashboard.</p></div></div><div className="settings-grid"><article className="panel integration-card"><div className="integration-logo">I</div><div><h3>Intervals.icu</h3><p>Read completed activities and wellness. Calendar write access remains off.</p>{connection ? <><span className="pill positive">Connected · {connection.scope}</span><small>Last sync: {connection.last_sync_at ? formatDateTime(connection.last_sync_at) : "not yet"}</small><small>{hasIntervalsVo2 ? "VO₂max data received from the connected source." : "Intervals.icu returned no VO₂max value in this athlete’s Wellness, activity, or profile data. A Garmin or other device can write VO₂max into Intervals Wellness; an estimate visible elsewhere inside Intervals may not be exposed by the standard API."}</small></> : <span className="pill muted-pill">Not connected</span>}</div><div className="integration-actions">{connection?.status === "active" ? <><button className="primary-button" disabled={Boolean(busy)} onClick={() => act("runPipeline", {}, "Sync and assessment pipeline completed")}>{busy === "runPipeline" ? "Syncing…" : "Sync now"}</button><button className="text-button danger" onClick={() => act("disconnectIntervals", {}, "Intervals.icu disconnected")}>Disconnect</button></> : <a className="primary-button link-button" href={`/api/intervals/connect?athleteId=${state.selectedAthlete?.id}`}>Connect my data</a>}</div></article>{coach && <article className="panel delivery-card"><p className="eyebrow">DELIVERY OUTBOX</p><h3>Notifications</h3><div className="delivery-list">{state.notifications.length ? state.notifications.map((item) => <div key={item.id}><span className={`delivery-status ${item.status}`} /> <strong>{item.subject}</strong><small>{item.status} · {formatDateTime(item.created_at)}</small></div>) : <p>No delivery events yet.</p>}</div></article>}</div>{coach && <section className="panel pipeline-panel"><div className="panel-header"><div><p className="eyebrow">BACKGROUND PIPELINE</p><h3>Recent jobs</h3></div></div><div className="stage-table"><table><thead><tr><th>Job</th><th>Scheduled</th><th>Status</th><th>Attempts</th><th>Detail</th></tr></thead><tbody>{state.jobs.length ? state.jobs.map((job) => <tr key={job.id}><td>{job.job_type.replaceAll("_", " ")}</td><td>{formatDateTime(job.scheduled_at)}</td><td><span className={`job-status ${job.status}`}>{job.status}</span></td><td>{job.attempts}</td><td>{job.last_error || "—"}</td></tr>) : <tr><td colSpan={5}>No background jobs yet.</td></tr>}</tbody></table></div></section>}</section>;
}

function SessionList({ sessions, expanded = false, coach = false, editable = false, canLog = false, busy = "", act }: { sessions: AnyRow[]; expanded?: boolean; coach?: boolean; editable?: boolean; canLog?: boolean; busy?: string; act?: (action:string,payload?:AnyRow,success?:string)=>void }) { return <div className="session-list">{sessions.length ? sessions.map((session) => { const race=String(session.workout_type).toLowerCase()==="race"; return <article className={`session ${expanded ? "expanded" : ""} ${race ? "race" : ""}`} key={session.id}><div className="session-date"><b>{weekday(session.session_date)}</b><span>{shortDate(session.session_date)}</span></div><div className={`session-icon ${session.major_stimulus ? "key" : ""} ${race ? "race" : ""}`}>{race ? "★" : session.major_stimulus ? "↗" : "·"}</div><div className="session-detail"><div className="session-title-line"><strong>{session.title}</strong>{race && <span className="session-race-label">Race</span>}{session.status !== "planned" && <span className={`session-state ${session.status}`}>{session.status}</span>}</div><span>{expanded ? session.details : session.pace_guidance || session.details}</span>{expanded && <small>{session.purpose}</small>}{expanded && editable && coach && act && <details className="session-actions"><summary>Edit draft session</summary><SessionEditForm session={session} busy={busy} submit={(values) => act("updatePlanSession", { sessionId: session.id, ...values }, "Draft session updated")} /></details>}{expanded && canLog && act && session.workout_type !== "rest" && <details className="session-actions"><summary>{session.status === "planned" ? "Log this session" : "Update session log"}</summary><SessionLogForm session={session} busy={busy} submit={(values) => act("logSession", { sessionId: session.id, ...values }, "Session log saved")} /></details>}</div><b className="session-distance">{Number(session.planned_distance_km) ? `${session.planned_distance_km} km` : "Rest"}</b></article>; }) : <div className="empty-inline">No sessions available.</div>}</div>; }

function SessionEditForm({ session, busy, submit }: { session:AnyRow; busy:string; submit:(values:AnyRow)=>void }) { function onSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();submit(Object.fromEntries(new FormData(event.currentTarget).entries()));} return <form className="session-editor" onSubmit={onSubmit}><div className="form-row"><Field name="sessionDate" label="Date" type="date" defaultValue={session.session_date} required /><Field name="plannedDistanceKm" label="Distance (km)" type="number" step="0.1" defaultValue={session.planned_distance_km ?? ""} /></div><Field name="title" label="Session title" defaultValue={session.title} required /><label className="field"><span>Workout details</span><textarea name="details" rows={3} defaultValue={session.details} required /></label><div className="form-row"><Field name="paceGuidance" label="Pace guidance" defaultValue={session.pace_guidance ?? ""} /><Field name="hrGuidance" label="HR guidance" defaultValue={session.hr_guidance ?? ""} /></div><Field name="purpose" label="Purpose" defaultValue={session.purpose ?? ""} /><label className="check-field"><input name="majorStimulus" type="checkbox" defaultChecked={Boolean(session.major_stimulus)} /> Key stimulus</label><button className="secondary-button" disabled={Boolean(busy)}>Save changes</button></form>; }
function SessionLogForm({ session, busy, submit }: { session:AnyRow; busy:string; submit:(values:AnyRow)=>void }) { function onSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();submit(Object.fromEntries(new FormData(event.currentTarget).entries()));} return <form className="session-editor" onSubmit={onSubmit}><div className="form-row"><label className="field"><span>Outcome</span><select name="status" defaultValue={session.status === "skipped" ? "skipped" : "completed"}><option value="completed">Completed</option><option value="skipped">Skipped</option></select></label><Field name="completionRpe" label="RPE (1–10)" type="number" min="1" max="10" defaultValue={session.completion_rpe ?? ""} /></div><div className="form-row"><Field name="actualDistanceKm" label="Actual distance (km)" type="number" step="0.1" defaultValue={session.actual_distance_km ?? ""} /><Field name="actualDurationMinutes" label="Duration (minutes)" type="number" defaultValue={session.actual_duration_minutes ?? ""} /></div><label className="field"><span>Comment for your coach</span><textarea name="athleteComment" rows={2} defaultValue={session.athlete_comment ?? ""} /></label><button className="primary-button" disabled={Boolean(busy)}>Save session log</button></form>; }
function Threshold({ label, pace, hr, lactate, help }: { label:string; pace:any; hr:any; lactate:any; help:string }) { return <div><span>{label} <button className="info-tip" type="button" aria-label={`About ${label}`} data-tooltip={help}>ⓘ</button></span><strong>{formatPace(pace)}</strong><p>{hr ? `${hr} bpm` : "HR —"} · {lactate ? `${lactate} mmol/L` : "lactate —"}</p></div>; }
function NavButton({ active, label, icon, badge, onClick }: { active:boolean; label:string; icon:string; badge?:string; onClick:()=>void }) { return <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick}><span>{icon}</span>{label}{badge && <b>{badge}</b>}</button>; }
function EmptyPanel({ title, body }: { title:string; body:string }) { return <div className="panel empty-panel"><span>○</span><h3>{title}</h3><p>{body}</p></div>; }
function LoadingScreen({ message }: { message?:string }) { return <div className="loading-screen"><img className="loading-logo" src="/personal-besties-logo-placeholder.png" alt="Personal Besties" /><h1>Preparing your coaching workspace</h1><p>{message || "Loading private athlete records…"}</p></div>; }
function EmptyWorkspace({ user, onInvite, modal, close, act, busy }: any) { return <div className="loading-screen"><img className="loading-logo" src="/personal-besties-logo-placeholder.png" alt="Personal Besties" /><h1>Welcome, {user.displayName}</h1><p>Invite your first athlete to begin.</p><button className="primary-button" onClick={onInvite}>Invite athlete</button>{modal && <ModalLayer modal="invite" athlete={null} close={close} act={act} busy={busy} />}</div>; }

function ModalLayer({ modal, athlete, close, act, busy }: { modal: Exclude<Modal,null>; athlete: AnyRow | null; close:()=>void; act:(a:string,p?:AnyRow,s?:string)=>void; busy:string }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) close(); }}><div className="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={close} aria-label="Close">×</button>
    {modal === "invite" && <InviteForm submit={(data) => act("inviteAthlete", data, "Athlete invited and delivery queued")} busy={busy} />}
    {modal === "goal" && <GoalForm submit={(data) => act("saveGoal", data, "Goal saved")} busy={busy} />}
    {modal === "test" && <TestForm submit={(data) => act("saveLactateTest", data, "Lactate test recorded")} busy={busy} />}
    {modal === "testRequest" && <TestRequestForm submit={(data) => act("requestLactateTest", data, "Your coach has been notified")} busy={busy} />}
    {modal === "performance" && <PerformanceForm submit={(data) => act("savePerformanceSnapshot", data, "Performance history updated")} busy={busy} />}
    {modal === "feedback" && <FeedbackForm submit={(data) => act("submitFeedback", data, "Check-in saved")} busy={busy} />}
    {modal === "profile" && athlete && <ProfileForm athlete={athlete} submit={(data) => act("updateAthlete", data, "Athlete profile updated")} busy={busy} />}
    {modal === "onboarding" && athlete && <OnboardingForm athlete={athlete} submit={(data) => act("completeOnboarding", data, "Your athlete profile is ready")} busy={busy} />}
  </div></div>;
}

function InviteForm({ submit, busy }: FormProps) { return <BasicForm title="Invite athlete" intro="Create their private profile and queue a secure invitation. They complete their training profile before a plan can be drafted." submit={submit} busy={busy} action="Invite athlete"><Field name="displayName" label="Full name" required /><Field name="email" label="Email" type="email" required /><Field name="weeklyTargetKm" label="Known current weekly running volume (km, optional)" type="number" /><Field name="timezone" label="Timezone" defaultValue="Europe/Vienna" /></BasicForm>; }
function GoalForm({ submit, busy }: FormProps) { return <BasicForm title="Add goal" intro="The highest-priority upcoming goal controls plan generation; terrain and ascent shape the sessions." submit={(values) => submit({ ...values, goalTimeSeconds: timeToSeconds(String(values.goalTime ?? "")) })} busy={busy} action="Save goal"><Field name="title" label="Race or goal" required /><Field name="eventDate" label="Event date" type="date" required /><div className="form-row"><Field name="distanceKm" label="Distance (km)" type="number" step="0.01" /><Field name="elevationGainM" label="Elevation gain (m+)" type="number" min="0" step="10" /></div><div className="form-row"><label className="field"><span>Terrain</span><select name="terrainType" defaultValue="road"><option value="road">Road</option><option value="trail">Trail</option><option value="mixed">Mixed</option><option value="track">Track</option><option value="other">Other</option></select></label><label className="field"><span>Trail technicality</span><select name="technicality" defaultValue="smooth"><option value="smooth">Smooth / runnable</option><option value="moderate">Moderate</option><option value="technical">Technical</option></select></label></div><Field name="goalTime" label="Goal time (HH:MM:SS)" placeholder="01:15:00" /><label className="field"><span>Priority</span><select name="priority" defaultValue="A"><option>A</option><option>B</option><option>C</option></select></label><label className="field"><span>Context and objective</span><textarea name="notes" rows={3} /></label></BasicForm>; }
function FeedbackForm({ submit, busy }: FormProps) { return <BasicForm title="Daily check-in" intro="Use your own perception; numbers are optional." submit={submit} busy={busy} action="Save check-in"><Field name="feedbackDate" label="Date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required /><div className="form-row"><Field name="fatigue" label="Fatigue (1–10)" type="number" min="1" max="10" /><Field name="legs" label="Legs (1–10)" type="number" min="1" max="10" /></div><div className="form-row"><Field name="sleep" label="Sleep (1–10)" type="number" min="1" max="10" /><Field name="rpe" label="Session RPE" type="number" min="1" max="10" /></div><Field name="pain" label="Pain or symptoms" placeholder="Location, onset, and how it changes movement" /><label className="field"><span>Comments</span><textarea name="comments" rows={3} /></label></BasicForm>; }
function ProfileForm({ athlete, submit, busy }: FormProps & { athlete:AnyRow }) { const availability=athlete.availability??{}; const pbs=availability.pacePersonalBests??{}; return <BasicForm title="Athlete profile" intro="Personal values are used only as a fallback when there is no recent lactate test or verified race result." submit={(values)=>submit({...values,availability:{...availability,maxHr:Number(values.maxHr)||null,pacePersonalBests:{fiveKSeconds:timeToSeconds(String(values.fiveK??""))||null,tenKSeconds:timeToSeconds(String(values.tenK??""))||null,halfSeconds:timeToSeconds(String(values.half??""))||null,marathonSeconds:timeToSeconds(String(values.marathon??""))||null}}})} busy={busy} action="Update profile"><Field name="displayName" label="Full name" defaultValue={athlete.displayName} required /><Field name="weeklyTargetKm" label="Current sustainable weekly running volume (km)" type="number" defaultValue={athlete.weeklyTargetKm ?? ""} /><p className="form-divider">ZONE FALLBACKS</p><Field name="maxHr" label="Maximum heart rate (bpm, optional)" type="number" min="100" max="240" defaultValue={availability.maxHr??""} /><p className="form-hint">Optional personal bests (HH:MM:SS). Enter only genuine best efforts.</p><div className="form-row"><Field name="fiveK" label="5 km PB" defaultValue={pbs.fiveKSeconds?formatDuration(pbs.fiveKSeconds):""} placeholder="00:20:00" /><Field name="tenK" label="10 km PB" defaultValue={pbs.tenKSeconds?formatDuration(pbs.tenKSeconds):""} placeholder="00:42:00" /></div><div className="form-row"><Field name="half" label="Half-marathon PB" defaultValue={pbs.halfSeconds?formatDuration(pbs.halfSeconds):""} placeholder="01:32:00" /><Field name="marathon" label="Marathon PB" defaultValue={pbs.marathonSeconds?formatDuration(pbs.marathonSeconds):""} placeholder="03:15:00" /></div><label className="field"><span>Injury / restriction context</span><textarea name="injuryNotes" rows={4} defaultValue={athlete.injuryNotes ?? ""} /></label></BasicForm>; }
function OnboardingForm({ athlete, submit, busy }: FormProps & { athlete:AnyRow }) {
  const availability = athlete.availability ?? {}; const selectedDays = Array.isArray(availability.preferredTrainingDays) ? availability.preferredTrainingDays : String(availability.preferredTrainingDays ?? "").split(",").map((day:string)=>day.trim()); const days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
  return <BasicForm title="Training profile" intro="This controls whether a draft can be generated, how many sessions it contains, and on which days. A coach still reviews every draft before publication." submit={(values)=>submit({...values,goalTimeSeconds:timeToSeconds(String(values.goalTime??""))})} busy={busy} action="Complete planning profile" wide>
    <p className="form-divider">SPORT & EXPERIENCE</p><div className="form-row"><label className="field"><span>Primary sport</span><select name="primarySport" defaultValue={athlete.primarySport??"running"}><option value="running">Running</option><option value="cycling">Cycling</option><option value="triathlon">Triathlon</option><option value="other">Another endurance sport</option></select></label><label className="field"><span>Experience</span><select name="experienceLevel" defaultValue={athlete.experienceLevel??"recreational"}><option value="new">New to the sport</option><option value="recreational">Recreational</option><option value="competitive">Competitive</option><option value="advanced">Advanced / high-performance</option></select></label></div><div className="form-row"><Field name="yearsInSport" label="Years in primary sport" type="number" min="0" step="0.5" defaultValue={availability.yearsInSport??""} /><Field name="weeklyTargetKm" label="Current sustainable weekly running volume (km)" type="number" min="0" step="0.5" defaultValue={athlete.weeklyTargetKm??""} /></div><div className="form-row"><Field name="longestRecentSessionKm" label="Longest run in the last 4 weeks (km)" type="number" min="0" step="0.5" defaultValue={availability.longestRecentSessionKm??""} /><Field name="otherEnduranceSports" label="Other endurance sports / usual volume" defaultValue={availability.otherEnduranceSports??""} placeholder="e.g. cycling 2 h/week" /></div>
    <p className="form-divider">AVAILABILITY</p><div className="form-row"><Field name="trainingDays" label="Days available and wanted per week" type="number" min="2" max="7" defaultValue={athlete.trainingDays??4} /><label className="field"><span>Preferred long-run day</span><select name="longRunDay" defaultValue={athlete.longRunDay??"Sunday"}>{days.map(day=><option key={day}>{day}</option>)}</select></label></div><fieldset className="training-day-field"><legend>Days normally available</legend><div>{days.map(day=><label key={day}><input type="checkbox" name="preferredTrainingDays" value={day} defaultChecked={selectedDays.includes(day)} />{day.slice(0,3)}</label>)}</div></fieldset><Field name="scheduleNotes" label="Schedule constraints" defaultValue={availability.scheduleNotes??""} placeholder="Travel, shifts, family commitments…" />
    <p className="form-divider">SAFETY & GOAL</p><label className="field"><span>Current pain, illness or restriction</span><select name="currentRestriction" defaultValue={availability.currentRestriction??"none"}><option value="none">None — able to train normally</option><option value="review">Something needs coach review before a draft</option><option value="medical">Medical restriction — no automated plan</option></select></label><label className="field"><span>Details for the coach</span><textarea name="injuryNotes" rows={3} defaultValue={athlete.injuryNotes??""} placeholder="Relevant injury history, pain, medication or restrictions. This is not a diagnosis." /></label><label className="check-field"><input type="checkbox" name="planReadinessConfirmed" value="yes" defaultChecked={Boolean(availability.planReadinessConfirmed)} />I confirm this is an honest current profile; any new pain or illness will be raised before training.</label><Field name="goalTitle" label="Race or goal" placeholder="Vienna Half Marathon" /><div className="form-row"><Field name="eventDate" label="Event date" type="date" /><Field name="distanceKm" label="Distance (km)" type="number" step="0.01" /></div><div className="form-row"><Field name="goalElevationGainM" label="Race elevation gain (m+)" type="number" min="0" step="10" /><label className="field"><span>Race terrain</span><select name="goalTerrainType" defaultValue="road"><option value="road">Road</option><option value="trail">Trail</option><option value="mixed">Mixed</option><option value="track">Track</option><option value="other">Other</option></select></label></div><label className="field"><span>Trail technicality</span><select name="goalTechnicality" defaultValue="smooth"><option value="smooth">Smooth / runnable</option><option value="moderate">Moderate</option><option value="technical">Technical</option></select></label><Field name="goalTime" label="Goal time (HH:MM:SS, optional)" placeholder="01:30:00" /><label className="field"><span>Goal context</span><textarea name="goalNotes" rows={2} /></label>
  </BasicForm>;
}
function TestForm({ submit, busy }: FormProps) {
  const [stages, setStages] = useState("3:00,4:30,140,1.2,2\n3:00,4:10,152,1.6,3\n3:00,3:50,164,2.4,5\n3:00,3:35,174,4.1,7");
  return <BasicForm title="Record lactate test" intro="Keep original stage data and derived thresholds together, with the interpretation method explicit." submit={(values) => submit({ ...values, lt1PaceSecondsKm: paceToSeconds(String(values.lt1Pace ?? "")), lt2PaceSecondsKm: paceToSeconds(String(values.lt2Pace ?? "")), stages: parseStages(stages) })} busy={busy} action="Save test" wide><div className="form-row"><Field name="testDate" label="Test date" type="date" required /><Field name="venue" label="Venue / lab" /></div><Field name="protocol" label="Protocol" placeholder="5 × 3 min treadmill stages, 1% incline" required /><div className="threshold-form"><h4>Derived LT1</h4><Field name="lt1Pace" label="Pace (MM:SS/km)" /><Field name="lt1Hr" label="HR" type="number" /><Field name="lt1Lactate" label="Lactate" type="number" step="0.1" /><h4>Derived LT2</h4><Field name="lt2Pace" label="Pace (MM:SS/km)" /><Field name="lt2Hr" label="HR" type="number" /><Field name="lt2Lactate" label="Lactate" type="number" step="0.1" /></div><Field name="interpretationMethod" label="Interpretation method" placeholder="Visual breakpoint + Dmax review" /><label className="field"><span>Stage data — duration, pace, HR, lactate, RPE</span><textarea value={stages} onChange={(event) => setStages(event.target.value)} rows={5} /><small>One stage per line. Example: 3:00,4:10,152,1.6,3</small></label><label className="field"><span>Confidence</span><select name="confidence" defaultValue="moderate"><option>low</option><option>moderate</option><option>high</option></select></label><label className="field"><span>Interpretation notes</span><textarea name="notes" rows={3} /></label></BasicForm>;
}
function TestRequestForm({ submit, busy }: FormProps) { return <BasicForm title="Request a lactate test" intro="Tell your coach when you would like to test. The request is saved in your dashboard and an email is queued for your coach." submit={submit} busy={busy} action="Send request"><Field name="preferredDate" label="Preferred date (optional)" type="date" /><Field name="availability" label="Your availability" placeholder="For example: weekday mornings or Friday after 15:00" /><label className="field"><span>Anything your coach should know?</span><textarea name="note" rows={3} placeholder="Testing goal, recent training, travel constraints…" /></label></BasicForm>; }
function PerformanceForm({ submit, busy }: FormProps) { return <BasicForm title="Add performance data" intro="Record a dated estimate from Garmin, Suunto, COROS, Intervals.icu, a lab, or your coaching model. Leave fields blank when the source does not provide them." submit={(values) => submit({ ...values, prediction5kSeconds:timeToSeconds(String(values.prediction5k ?? "")), prediction10kSeconds:timeToSeconds(String(values.prediction10k ?? "")), predictionHalfSeconds:timeToSeconds(String(values.predictionHalf ?? "")), predictionMarathonSeconds:timeToSeconds(String(values.predictionMarathon ?? "")) })} busy={busy} action="Add to history" wide><div className="form-row"><Field name="snapshotDate" label="Date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required /><label className="field"><span>Source</span><select name="source" defaultValue="Garmin"><option>Garmin</option><option>Suunto</option><option>COROS</option><option>Intervals.icu</option><option>Lab</option><option>Personal Besties model</option><option>Manual</option></select></label></div><Field name="vo2max" label="VO₂max" type="number" step="0.1" /><div className="form-row"><Field name="prediction5k" label="5K prediction" placeholder="00:17:30" /><Field name="prediction10k" label="10K prediction" placeholder="00:36:30" /></div><div className="form-row"><Field name="predictionHalf" label="Half-marathon prediction" placeholder="01:18:00" /><Field name="predictionMarathon" label="Marathon prediction" placeholder="02:45:00" /></div></BasicForm>; }

type FormProps = { submit:(values:AnyRow)=>void; busy:string };
function BasicForm({ title, intro, submit, busy, action, children, wide=false }: FormProps & { title:string; intro:string; action:string; children:React.ReactNode; wide?:boolean }) {
  function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values:AnyRow={}; for(const [key,value] of new FormData(event.currentTarget).entries()){if(key in values)values[key]=Array.isArray(values[key])?[...values[key],value]:[values[key],value];else values[key]=value;} submit(values); }
  return <form className={`modal-form ${wide ? "wide" : ""}`} onSubmit={onSubmit}><p className="eyebrow">PRIVATE WORKSPACE</p><h2 id="modal-title">{title}</h2><p className="form-intro">{intro}</p>{children}<button className="primary-button form-submit" disabled={Boolean(busy)}>{busy ? "Working…" : action}</button></form>;
}
function Field(props: AnyRow) { const { label, ...inputProps } = props; return <label className="field"><span>{label}</span><input {...inputProps} /></label>; }

function initials(name:string) { return name.split(/\s+/).slice(0,2).map((part) => part[0]).join("").toUpperCase(); }
function dayPart() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }
function athleteStatus(athlete:AnyRow,state:WorkspaceState) { if (athlete.status === "invited") return "Invitation pending"; const setup=athlete.setup??{}; const complete=Object.values(setup).filter(Boolean).length; if(complete<5)return `Setup ${complete}/5`; if (athlete.id === state.selectedAthlete?.id) return state.metrics.recoveryStatus; return "Ready"; }
function connectionStatus(connections:AnyRow[], language:Language="en") { const connection = connections.find((item) => item.status === "active"); const de=language==="de"; return <span className="sync-state"><i />{connection ? `${de?"Synchronisiert":"Synced"} ${connection.last_sync_at ? formatRelative(connection.last_sync_at, language) : (de?"ausständig":"pending")}` : (de?"Manuelle Daten":"Manual data")}</span>; }
function formatDuration(value:any) { const total = Number(value); if (!Number.isFinite(total)) return "—"; const hours=Math.floor(total/3600),minutes=Math.floor((total%3600)/60),seconds=Math.round(total%60); return hours ? `${hours}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}` : `${minutes}:${String(seconds).padStart(2,"0")}`; }
function formatPace(value:any) { const total=Number(value); return Number.isFinite(total)&&total>0 ? `${Math.floor(total/60)}:${String(Math.round(total%60)).padStart(2,"0")}/km` : "—"; }
function formatDate(value:any, language:Language="en") { if(!value)return "—"; return new Date(`${String(value).slice(0,10)}T12:00:00Z`).toLocaleDateString(language==="de"?"de-AT":"en",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}); }
function formatDateTime(value:any, language:Language="en") { if(!value)return "—"; return new Date(value).toLocaleString(language==="de"?"de-AT":"en",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}); }
function formatRelative(value:string, language:Language="en") { const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000)); if(language==="de")return minutes<2?"gerade eben":minutes<60?`vor ${minutes} Min.`:`vor ${Math.round(minutes/60)} Std.`; return minutes<2?"just now":minutes<60?`${minutes} min ago`:`${Math.round(minutes/60)} h ago`; }
function weekday(value:string) { return new Date(`${value}T12:00:00Z`).toLocaleDateString("en",{weekday:"short",timeZone:"UTC"}).toUpperCase(); }
function shortDate(value:string) { return new Date(`${value}T12:00:00Z`).toLocaleDateString("en",{day:"numeric",month:"short",timeZone:"UTC"}); }
function timeToSeconds(value:string) { if(!value)return null; const parts=value.split(":").map(Number); if(parts.some((part)=>!Number.isFinite(part)))return null; return parts.length===3?parts[0]*3600+parts[1]*60+parts[2]:parts[0]*60+parts[1]; }
function paceToSeconds(value:string) { const parts=value.split(":").map(Number); return parts.length===2&&parts.every(Number.isFinite)?parts[0]*60+parts[1]:null; }
function parseStages(value:string) { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [duration,pace,heartRate,lactateMmol,rpe]=line.split(",").map((part)=>part.trim()); return { durationSeconds:timeToSeconds(duration),paceSecondsKm:paceToSeconds(pace),heartRate:Number(heartRate)||null,lactateMmol:Number(lactateMmol),rpe:Number(rpe)||null }; }).filter((stage)=>Number.isFinite(stage.lactateMmol)); }
function chartColor(index:number) { return ["#2d6f58","#d17a45","#6b67a8","#b2546c"][index % 4]; }
function distanceLabel(distance:string) { return distance === "5k" ? "5K" : distance === "10k" ? "10K" : distance === "marathon" ? "Marathon" : "Half-marathon"; }
function filterRange<T extends {date:string}>(points:T[], range:string) { if(range === "all") return points; const months=range === "3m"?3:range === "6m"?6:12; const cutoff=new Date(); cutoff.setMonth(cutoff.getMonth()-months); return points.filter((point)=>new Date(`${point.date}T12:00:00Z`)>=cutoff); }

function localRecovery(value:string, language:Language) { if(language!=="de")return value; return ({"Check in":"Check-in fehlt","Review pain":"Schmerz prüfen","Recover":"Erholen","Caution":"Vorsicht","Ready":"Bereit"} as Record<string,string>)[value]??value; }

function buildActivityReviews(activities:AnyRow[], sessions:AnyRow[], latestTest:AnyRow|undefined, language:Language) {
  const de=language==="de", today=new Date().toISOString().slice(0,10), byDate=new Map<string,AnyRow[]>();
  for(const activity of activities){if(!isRunActivity(activity.activity_type))continue;const date=String(activity.activity_date);byDate.set(date,[...(byDate.get(date)??[]),activity]);}
  const reviews:any[]=[];
  for(const activity of activities.slice(0,20)){
    const date=String(activity.activity_date), running=isRunActivity(activity.activity_type), planned=running?sessions.find((session)=>session.session_date===date&&session.workout_type!=="rest"):undefined;
    const race=isRaceActivity(activity);
    const pace=Number(activity.duration_seconds)/Math.max(.01,Number(activity.distance_km)), hr=Number(activity.average_hr), range=parsePaceRange(String(planned?.pace_guidance??""));
    let tone="good",badge=de?"GUT ERLEDIGT":"WELL DONE",summary=de?"Die Einheit wurde sauber abgeschlossen.":"The session was completed with useful training evidence.",detail=`${Number(activity.distance_km??0).toFixed(1)} km · ${formatPace(pace)}${hr>40?` · ${Math.round(hr)} bpm`:""}`;
    if(!running) {tone="neutral";badge=de?"CROSS-TRAINING":"CROSS-TRAINING";summary=de?"Diese Einheit wird als Cross-Training geführt. Sie wird weder als Lauf noch gegen Laufpace-Vorgaben bewertet.":"This is cross-training. It is neither counted as a run nor judged against running pace guidance.";detail=`${activity.activity_type||"Activity"} · ${formatDuration(Number(activity.duration_seconds))}${hr>40?` · ${Math.round(hr)} bpm`:""}`;}
    else if(planned?.status==="skipped") {tone="warning";badge=de?"WIDERSPRUCH":"MISMATCH";summary=de?"Im Plan als ausgelassen markiert, aber eine Aktivität wurde synchronisiert. Bitte den Eintrag prüfen.":"The plan says skipped, but an activity was synchronized. Review the session log.";}
    else if(range&&pace<range[0]-5){tone="warning";badge=de?"ZU SCHNELL":"TOO FAST";summary=de?`Schneller als die Vorgabe ${formatPace(range[0])}–${formatPace(range[1])}. Das war nicht automatisch besser und kann zusätzliche Ermüdung erzeugen.`:`Faster than the ${formatPace(range[0])}–${formatPace(range[1])} guidance. Faster was not automatically better and may add unnecessary fatigue.`;}
    else if(planned&&["recovery","easy","long_run"].includes(String(planned.workout_type))&&latestTest?.lt1_hr&&hr>Number(latestTest.lt1_hr)+7){tone="warning";badge=de?"HF HOCH":"HR HIGH";summary=de?"Für eine lockere Einheit lag die durchschnittliche Herzfrequenz deutlich über LT1. Erholung und Bedingungen prüfen.":"Average heart rate was clearly above LT1 for an easy session. Review recovery and conditions.";}
    else if(!planned){tone="neutral";badge=de?"ZUSATZ":"UNPLANNED";summary=de?"Aktivität ohne passende Planeinheit. Kann sinnvoll sein, sollte aber in die Wochenbelastung einfließen.":"No matching planned session. It may be fine, but it still counts toward weekly load.";}
    if(running&&planned?.planned_distance_km){const delta=Number(activity.distance_km)-Number(planned.planned_distance_km);detail+=` · Plan ${Number(planned.planned_distance_km).toFixed(1)} km (${delta>=0?"+":""}${delta.toFixed(1)} km)`;}
    if(race) badge=de?"WETTKAMPF":"RACE";
    reviews.push({key:`activity-${activity.id}`,date,title:activity.name||activity.activity_type||"Activity",tone,badge,summary,detail,race});
  }
  for(const session of sessions.filter((item)=>item.session_date<today&&item.workout_type!=="rest"&&item.status!=="completed").slice(-14)){
    if(byDate.has(String(session.session_date)))continue;
    const skipped=session.status==="skipped";
    reviews.push({key:`missed-${session.id}`,date:session.session_date,title:session.title,tone:"bad",badge:skipped?(de?"AUSGELASSEN":"SKIPPED"):(de?"NICHT ERFASST":"NOT DONE"),summary:skipped?(de?"Die Einheit wurde ausgelassen. Ehrlich erfasst ist besser als schöngefärbt—entscheidend ist die passende Reaktion.":"The session was skipped. Honest logging is more useful than perfect-looking data—the response matters now."):(de?"Keine passende Aktivität gefunden. Als erledigt markieren oder bewusst auslassen.":"No matching activity was found. Log it accurately or mark it skipped."),detail:session.pace_guidance||session.purpose||"—"});
  }
  return reviews.sort((a,b)=>String(b.date).localeCompare(String(a.date)));
}

function parsePaceRange(value:string):[number,number]|null { const matches=[...value.matchAll(/(\d{1,2}):(\d{2})/g)].map((match)=>Number(match[1])*60+Number(match[2])); return matches.length>=2?[Math.min(matches[0],matches[1]),Math.max(matches[0],matches[1])]:null; }
function isRunActivity(value:unknown) { return /run/i.test(String(value??"")); }
type ZoneShare = { label:string; hint:string; count:number; total:number; share:number };
type PaceZoneResult = { zones:ZoneShare[]|null; source:string };
type WeightedValue = { value:number; seconds:number };
function weightedZones(values:WeightedValue[], labels:string[], hints:string[], zoneFor:(value:number)=>number):ZoneShare[]|null { const total=values.reduce((sum,item)=>sum+item.seconds,0); if(!total)return null; const seconds=labels.map(()=>0); for(const item of values) seconds[Math.max(0,Math.min(labels.length-1,zoneFor(item.value)))]+=item.seconds; return labels.map((label,index)=>({label,hint:hints[index],count:Math.round(seconds[index]/60),total:Math.round(total/60),share:Math.round(seconds[index]/total*100)})); }
function activityWeightedValues(activities:AnyRow[], valueFor:(item:AnyRow)=>number) { return activities.map((item)=>({value:valueFor(item),seconds:Number(item.duration_seconds)})).filter((item)=>Number.isFinite(item.value)&&Number.isFinite(item.seconds)&&item.seconds>0); }
function sessionPaceZones(activities:AnyRow[], tests:AnyRow[], allActivities:AnyRow[], athlete:AnyRow|null):PaceZoneResult|null {
  const today=Date.now();
  const candidates=allActivities.map(racePaceEvidence).filter((item):item is RacePaceEvidence=>Boolean(item));
  const currentRace=bestRaceEvidence(candidates.filter((item)=>item.ageDays<=180));
  const pb=bestRaceEvidence(candidates);
  const fastestRun=bestFastestRunEvidence(allActivities.filter((activity)=>daysSince(activity.activity_date,today)<=180));
  const profilePb=profilePaceEvidence(athlete?.availability);
  const test=tests.find((item)=>Number(item.lt2_pace_seconds_km)>120&&Number(item.lt2_pace_seconds_km)<900);
  const testAge=test?daysSince(test.test_date,today):Infinity;
  const testPace=Number(test?.lt2_pace_seconds_km);
  let anchor:number|undefined,source="";
  if(test&&testAge<=180){
    if(currentRace&&Math.abs(currentRace.marathonPace-testPace)/testPace>.07){ anchor=Math.round(testPace*.4+currentRace.marathonPace*.6); source=`Lactate test ${formatDate(test.test_date)} adjusted to recent ${currentRace.distanceLabel} result ${formatDate(currentRace.date)}.`; }
    else { anchor=testPace; source=`Latest lactate test · LT2 ${formatPace(testPace)} · ${formatDate(test.test_date)}.`; }
  } else if(test&&testAge<=365&&currentRace){ anchor=Math.round(testPace*.45+currentRace.marathonPace*.55); source=`Older lactate test ${formatDate(test.test_date)} blended with recent ${currentRace.distanceLabel} result ${formatDate(currentRace.date)}.`; }
  else if(currentRace){ anchor=currentRace.marathonPace; source=`Current ${currentRace.distanceLabel} result · ${formatDuration(currentRace.durationSeconds)} · ${formatDate(currentRace.date)}.`; }
  else if(profilePb){ anchor=profilePb.marathonPace; source=`Profile PB · ${profilePb.distanceLabel} ${formatDuration(profilePb.durationSeconds)} · provisional until a recent test or race is available.`; }
  else if(fastestRun){ anchor=fastestRun.marathonPace; source=`Fastest suitable run · ${formatDuration(fastestRun.durationSeconds)} over ${fastestRun.distanceLabel} · ${formatDate(fastestRun.date)} · provisional.`; }
  else if(test&&testAge<=365){ anchor=testPace; source=`Lactate test ${formatDate(test.test_date)} · provisional because it is ${Math.round(testAge)} days old.`; }
  else if(pb){ anchor=pb.marathonPace; source=`Historical ${pb.distanceLabel} PB · ${formatDuration(pb.durationSeconds)} · ${formatDate(pb.date)} · provisional.`; }
  if(!anchor)return null;
  // Ratios reproduce a 2:42 marathon reference (3:50/km) as 4:42, 4:03,
  // 3:38, 3:24 and 3:12/km, while scaling sensibly for other abilities.
  const bounds=[Math.round(anchor*1.226),Math.round(anchor*1.057),Math.round(anchor*.948),Math.round(anchor*.887),Math.round(anchor*.835)];
  const labels=["Z1 · Recovery","Z2 · Endurance","Z3 · Tempo","Z4 · Threshold","Z5 · VO₂max","Z6 · Anaerobic"];
  const hints=[`≥ ${formatPace(bounds[0])}`,`${formatPace(bounds[1])}–${formatPace(bounds[0])}`,`${formatPace(bounds[2])}–${formatPace(bounds[1])}`,`${formatPace(bounds[3])}–${formatPace(bounds[2])}`,`${formatPace(bounds[4])}–${formatPace(bounds[3])}`,`< ${formatPace(bounds[4])}`];
  const stream=paceStreamValues(activities);
  const zones=weightedZones(stream.values,labels,hints,(value)=>value>=bounds[0]?0:value>=bounds[1]?1:value>=bounds[2]?2:value>=bounds[3]?3:value>=bounds[4]?4:5);
  return {zones,source:zones?`${source} Exact pace-stream samples from ${stream.activities} ${stream.activities===1?"activity":"activities"}; runs without a source stream are excluded.`:`${source} No pace-stream samples are available in this selection yet.`};
}
function paceStreamValues(activities:AnyRow[]) { const values:WeightedValue[]=[]; let activityCount=0; for(const activity of activities){ const raw=rawActivity(activity),modern=raw.pb_activity_stream_v2,legacy=raw.pb_pace_stream_v1; const histogram=Array.isArray(modern?.pace_histogram)?modern.pace_histogram:(Array.isArray(legacy?.histogram)?legacy.histogram:[]); let used=false; for(const row of histogram){ const pace=Number(row?.[0]),seconds=Number(row?.[1]); if(Number.isFinite(pace)&&pace>120&&pace<900&&Number.isFinite(seconds)&&seconds>0){values.push({value:pace,seconds});used=true;} } if(used)activityCount++; } return {values,activities:activityCount}; }
type RacePaceEvidence={date:string;ageDays:number;distanceLabel:string;durationSeconds:number;marathonPace:number};
function racePaceEvidence(activity:AnyRow):RacePaceEvidence|null { const distance=Number(activity.distance_km),duration=Number(activity.duration_seconds),elevation=Number(activity.elevation_gain_m??0),date=String(activity.activity_date??"").slice(0,10); const standard=[[5,"5k"],[10,"10k"],[21.0975,"half-marathon"],[42.195,"marathon"]] as const; const matched=standard.find(([target])=>distance>=target*.92&&distance<=target*1.08); if(!matched||!isRunActivity(activity.activity_type)||!Number.isFinite(duration)||duration<900||!date||elevation/distance>25||!(isRaceActivity(activity)||/time.?trial|\btest\b|\b5\s?k\b|\b10\s?k\b/i.test(String(activity.name??""))))return null; const ageDays=daysSince(date,Date.now()); if(ageDays<0)return null; return {date,ageDays,distanceLabel:matched[1],durationSeconds:duration,marathonPace:duration*Math.pow(42.195/distance,1.06)/42.195}; }
function bestRaceEvidence(items:RacePaceEvidence[]) { return [...items].sort((a,b)=>(a.marathonPace+Math.min(a.ageDays,730)*.12)-(b.marathonPace+Math.min(b.ageDays,730)*.12))[0]; }
function fastestRunEvidence(activity:AnyRow):RacePaceEvidence|null { const distance=Number(activity.distance_km),duration=Number(activity.duration_seconds),elevation=Number(activity.elevation_gain_m??0),date=String(activity.activity_date??"").slice(0,10); if(!isRunActivity(activity.activity_type)||!Number.isFinite(distance)||distance<3||distance>45||!Number.isFinite(duration)||duration<900||!date||elevation/distance>25)return null; return {date,ageDays:daysSince(date),distanceLabel:`${distance.toFixed(1)} km`,durationSeconds:duration,marathonPace:duration*Math.pow(42.195/distance,1.06)/42.195}; }
function bestFastestRunEvidence(activities:AnyRow[]) { return bestRaceEvidence(activities.map(fastestRunEvidence).filter((item):item is RacePaceEvidence=>Boolean(item))); }
function profilePaceEvidence(availability:unknown):RacePaceEvidence|null { const profile=availability&&typeof availability==="object"?availability as AnyRow:{}; const pbs=profile.pacePersonalBests&&typeof profile.pacePersonalBests==="object"?profile.pacePersonalBests as AnyRow:{}; const values:[string,number,unknown][]=[["5k",5,pbs.fiveKSeconds],["10k",10,pbs.tenKSeconds],["half-marathon",21.0975,pbs.halfSeconds],["marathon",42.195,pbs.marathonSeconds]]; const candidates=values.map(([distanceLabel,distance,value])=>{const durationSeconds=Number(value); return Number.isFinite(durationSeconds)&&durationSeconds>=900&&durationSeconds<43_200?{date:"",ageDays:Infinity,distanceLabel,durationSeconds,marathonPace:durationSeconds*Math.pow(42.195/distance,1.06)/42.195}:null;}).filter((item):item is RacePaceEvidence=>Boolean(item)); return candidates.sort((a,b)=>a.marathonPace-b.marathonPace)[0]??null; }
function daysSince(value:unknown,now=Date.now()) { const date=new Date(`${String(value).slice(0,10)}T12:00:00Z`).getTime(); return Number.isFinite(date)?Math.max(0,(now-date)/86_400_000):Infinity; }
function sessionHrZones(activities:AnyRow[], tests:AnyRow[], athlete:AnyRow|null):PaceZoneResult|null { const test=tests.find((item)=>{const sim=String(item.interpretation_method??"").includes("SIM_5_HR_ZONES_V1"),lt1=Number(item.lt1_hr),lt2=Number(item.lt2_hr); return sim||Number.isFinite(lt1)&&Number.isFinite(lt2)&&lt2>lt1; }); const sim=String(test?.interpretation_method??"").includes("SIM_5_HR_ZONES_V1"); const testAge=test?daysSince(test.test_date):Infinity; const lt1=Number(test?.lt1_hr),lt2=Number(test?.lt2_hr),maxHr=Number(athlete?.availability?.maxHr); let bounds:number[]|null=null,source=""; if(test&&testAge<=365){ bounds=sim?[145,162,171,178]:[lt1-12,lt1,Math.round((lt1+lt2)/2),lt2]; source=`Lactate test ${formatDate(test.test_date)}.`; } else if(Number.isFinite(maxHr)&&maxHr>=100&&maxHr<=240){ bounds=[.6,.7,.8,.9].map((ratio)=>Math.round(maxHr*ratio)); source=`Profile maximum HR ${Math.round(maxHr)} bpm · provisional because there is no lactate test from the last year.`; } if(!bounds||bounds.some((value)=>!Number.isFinite(value)||value<=0)||bounds.some((value,index)=>index>0&&value<=bounds![index-1]))return null; const labels=sim?["REG","GA-ext","GA-int","SB","SB+"]:["HR Z1","HR Z2","HR Z3","HR Z4","HR Z5"]; const hints=[`<${bounds[0]} bpm`,`${bounds[0]}–${bounds[1]} bpm`,`${bounds[1]}–${bounds[2]} bpm`,`${bounds[2]}–${bounds[3]} bpm`,`≥${bounds[3]} bpm`]; const stream=heartRateStreamValues(activities); const zones=weightedZones(stream.values,labels,hints,(value)=>value<bounds![0]?0:value<bounds![1]?1:value<bounds![2]?2:value<bounds![3]?3:4); return {zones,source:zones?`${source} Exact heart-rate stream samples from ${stream.activities} ${stream.activities===1?"activity":"activities"}; activities without an HR stream are excluded.`:`${source} No HR-stream samples are available in this selection yet.`}; }
function heartRateStreamValues(activities:AnyRow[]) { const values:WeightedValue[]=[]; let activityCount=0; for(const activity of activities){ const cache=rawActivity(activity).pb_activity_stream_v2; const histogram=Array.isArray(cache?.heart_rate_histogram)?cache.heart_rate_histogram:[]; let used=false; for(const row of histogram){ const bpm=Number(row?.[0]),seconds=Number(row?.[1]); if(Number.isFinite(bpm)&&bpm>=40&&bpm<=240&&Number.isFinite(seconds)&&seconds>0){values.push({value:bpm,seconds});used=true;} } if(used)activityCount++; } return {values,activities:activityCount}; }
function activitySport(value:unknown) { const type=String(value??"").toLowerCase(); return /run/.test(type)?"run":/(ride|cycl|bike)/.test(type)?"cycle":"other"; }
function filterActivitiesBySport(activities:AnyRow[], sport:string) { return sport==="all"?activities:activities.filter((item)=>activitySport(item.activity_type)===sport); }
function rawActivity(activity:AnyRow) { try { return JSON.parse(String(activity.raw_summary_json??"{}")) as AnyRow; } catch { return {}; } }
function isRaceActivity(activity:AnyRow) { const raw=rawActivity(activity); if(raw.race===true||raw.race===1||String(raw.race).toLowerCase()==="true")return true; return /\b(race|wettkampf|marathon|halbmarathon|half marathon|parkrun)\b/i.test(String(activity.name??"")); }
function activityWatts(activity:AnyRow) { const raw=rawActivity(activity); for(const value of [activity.average_watts,activity.averageWatts,raw.average_watts,raw.averageWatts,raw.icu_average_watts,raw.avg_watts]){const watts=Number(value);if(Number.isFinite(watts)&&watts>0&&watts<2000)return watts;} return null; }
function filterActivityRange(activities:AnyRow[], range:string) { if(range==="all")return activities; const days=range==="7d"?7:range==="30d"?30:range==="90d"?90:range==="180d"?180:365; const cutoff=new Date(); cutoff.setDate(cutoff.getDate()-days); return activities.filter((item)=>new Date(`${String(item.activity_date)}T12:00:00Z`)>=cutoff); }
function realPerformancePoints(activities:AnyRow[], distance:string) { const target=distance==="5k"?5:distance==="10k"?10:distance==="half"?21.0975:42.195; return activities.filter((item)=>isRunActivity(item.activity_type)&&Number(item.distance_km)>target*.92&&Number(item.distance_km)<target*1.08&&Number(item.duration_seconds)>0).map((item)=>({date:String(item.activity_date),value:Number(item.duration_seconds),source:`${isRaceActivity(item)?"Race":"Real effort"}: ${item.name||`${Number(item.distance_km).toFixed(1)} km`}`,kind:(isRaceActivity(item)?"race":"effort") as const})); }
function median(values:number[]) { const sorted=[...values].sort((a,b)=>a-b), middle=Math.floor(sorted.length/2); return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2; }
